version: "2"

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - godoclint
    - godot
    #- godox
    - goheader
    - goprintffuncname
    - govet
    - ineffassign
    - intrange
    - ireturn
    - makezero
    - mirror
    - misspell
    # - mnd
    - modernize
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tagalign
    - thelper
    - usetesting
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
        # Allow common go-git interfaces
        - github.com/go-git/go-git/v5/plumbing/transport.AuthMethod
        # Allow internal project interfaces for dependency injection
        - git.home.luguber.info/inful/docbuilder/internal/forge.Client
        - git.home.luguber.info/inful/docbuilder/internal/hugo.RepoFetcher
        - git.home.luguber.info/inful/docbuilder/internal/hugo/commands.StageCommand
        - git.home.luguber.info/inful/docbuilder/internal/hugo/models.TypedTransformer
        - git.home.luguber.info/inful/docbuilder/internal/hugo/models.ConfigProvider
        - git.home.luguber.info/inful/docbuilder/internal/hugo/models.EditLinkResolver
        - git.home.luguber.info/inful/docbuilder/internal/lint.Formatter
        - git.home.luguber.info/inful/docbuilder/internal/metrics.Recorder
        - git.home.luguber.info/inful/docbuilder/internal/state.Store
        - git.home.luguber.info/inful/docbuilder/internal/state.RepositoryStore
        - git.home.luguber.info/inful/docbuilder/internal/state.BuildStore
        - git.home.luguber.info/inful/docbuilder/internal/state.ScheduleStore
        - git.home.luguber.info/inful/docbuilder/internal/state.StatisticsStore
        - git.home.luguber.info/inful/docbuilder/internal/state.ConfigurationStore
        - git.home.luguber.info/inful/docbuilder/internal/state.DaemonInfoStore
    tagalign:
      sort: true
      strict: false
      align: false
      order:
        - "cmd"
        - "short"
        - "name"
        - "default"
        - "env"
        - "help"
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - performance
    govet:
      enable:
        - shadow
    goconst:
      ignore-string-values:
        - "false"
    misspell:
      locale: US
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    unused:
      field-writes-are-uses: false
      post-statements-are-reads: true
      exported-fields-are-used: false
      local-variables-are-used: false
      generated-is-used: false

formatters:
  enable:
    # - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(git.home.luguber.info/inful/docbuilder)