# Comprehensive linter configuration balancing quality and practicality
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Core static analysis (already enabled)
    - govet
    - staticcheck
    - typecheck
    - gosimple
    - unused
    
    # Error handling
    - errcheck      # Checks for unchecked errors
    - errorlint     # Finds code that will cause problems with Go 1.13+ error wrapping
    
    # Code quality
    - revive        # Drop-in replacement for golint with more rules
    - gocyclo       # Detects cyclomatic complexity > 15
    - gocognit      # Detects cognitive complexity (readability metric)
    - dupl          # Finds code duplicates (100+ lines)
    - goconst       # Finds repeated strings that could be constants
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters
    
    # Security
    - gosec         # Security audit
    
    # Style & best practices
    - misspell      # Fixes commonly misspelled English words
    - gofmt         # Checks whether code was gofmt-ed
    - goimports     # Checks import order and unused imports
    - whitespace    # Detects trailing whitespace and unnecessary blank lines
    - predeclared   # Finds code that shadows predeclared identifiers
    
    # Performance
    - prealloc      # Finds slice declarations that could pre-allocate capacity
    
    # Correctness
    - nilerr        # Finds code returning nil even if error is not nil
    - nilnil        # Checks for simultaneous return of nil error and nil value
    - makezero      # Finds slice declarations with non-zero initial length
    
    # Maintainability  
    - godox         # Detects FIXME, TODO, BUG comments
    - gocritic      # Meta-linter with opinionated checks (comprehensive)

linters-settings:
  gocyclo:
    min-complexity: 20  # Allow moderate complexity in pipeline/daemon code
  
  gocognit:
    min-complexity: 30  # Cognitive complexity threshold
  
  dupl:
    threshold: 120      # Lines of code for duplication detection
  
  goconst:
    min-len: 3          # Minimum length of string constant
    min-occurrences: 3  # Minimum occurrences to trigger
    ignore-tests: true  # Don't flag test strings
  
  gosec:
    excludes:
      - G104  # Audited: errors checked where critical
      - G204  # Audited: subprocess calls in test code only
  
  revive:
    rules:
      - name: unused-parameter
        disabled: false
      - name: exported
        disabled: true  # Too noisy for internal packages
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam      # Structs passed by value intentionally (config snapshots)
      - rangeValCopy   # Sometimes clearer than pointers
  
  errcheck:
    check-type-assertions: true
    check-blank: false  # Don't flag `_ = expr`
  
  errorlint:
    errorf: true        # Check fmt.Errorf %w wrapping
    asserts: true       # Check error assertions
    comparison: true    # Check direct error comparisons
  
  unparam:
    check-exported: false  # Only check private functions
  
  prealloc:
    simple: true        # Only flag simple cases
    range-loops: true
    for-loops: false    # Too many false positives

issues:
  # Exclude specific issues
  exclude-rules:
    # Allow complexity in daemon/pipeline orchestration
    - path: internal/(daemon|pipeline)/
      linters:
        - gocyclo
        - gocognit
    
    # Allow complexity in config validation
    - path: internal/config/
      linters:
        - gocyclo
    
    # Test code exemptions - tests naturally have higher complexity
    - path: _test\.go
      linters:
        - dupl          # Duplicate test setup acceptable
        - goconst       # Test strings can repeat
        - gosec         # Security less critical in tests
        - errcheck      # Some test errors intentionally ignored
        - gocognit      # Test complexity acceptable
        - gocyclo       # Test cyclomatic complexity acceptable
    
    # Generated/mock code
    - path: internal/testforge/
      linters:
        - dupl
        - goconst
        - gocognit

    # Mock factories are intentionally repetitive for readability in tests
    - path: internal/forge/enhanced_mock_factory\.go
      linters:
        - dupl
    
    # Forge test integration files - intentionally complex integration tests
    - path: internal/forge/.*_(integration|workflow|deployment|summary|demo)_test\.go
      linters:
        - gocognit
        - gocyclo
        - dupl
    
    # Error adapters use type assertions intentionally for performance
    - path: internal/(errors|foundation/errors)/.*_adapter\.go
      linters:
        - errorlint  # Type assertions are intentional here for specific error types
    
    # Exclude TODO comments in specific files (tracked issues)
    - path: internal/hugo/(transforms|models)/
      linters:
        - godox
  
  # Maximum issues count (0 = unlimited)
  max-issues-per-linter: 50  # Limit per linter for manageable fixes
  max-same-issues: 10         # Limit duplicates
  
  # Show only new issues in CI (disabled for now to see everything)
  new: false
