name: Build and Push DocBuilder Multi-Arch Images (Docker Buildx)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      hugo_version:
        description: 'Hugo version to use'
        required: false
        default: '0.151.0'
        type: string
      push_images:
        description: 'Push images to registry'
        required: false
        default: true
        type: boolean

env:
  REGISTRY: git.home.luguber.info
  IMAGE_REPO: ${{ github.repository }}
  HUGO_VERSION: ${{ github.event.inputs.hugo_version || '0.151.0' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:dind
        options: --privileged

    strategy:
      matrix:
        target:
          - name: runtime-minimal
            suffix: ''
            description: 'Minimal runtime (distroless)'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      run: |
        echo "ðŸ”§ Setting up Docker Buildx for multi-arch builds..."
        
        # Check if buildx is available
        docker buildx version
        
        # Create and use a new builder instance for multi-arch
        docker buildx create --name multiarch --driver docker-container --use --bootstrap
        
        # Verify multi-arch support
        docker buildx inspect --bootstrap
        
        echo "âœ… Docker Buildx ready for multi-arch builds"

    - name: Extract version info
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=$(git rev-parse --short=7 HEAD)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "ðŸ·ï¸  Using version: $VERSION"
        
        # Extract branch name for additional tags
        BRANCH=$(echo "$GITHUB_REF_NAME" | sed 's/\//-/g')
        echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        echo "ðŸŒ¿ Branch: $BRANCH"

    - name: Check for registry credentials
      id: check_creds
      env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME || github.actor }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}
      run: |
        PUSH_ENABLED="${{ github.event.inputs.push_images }}"
        if [ "$PUSH_ENABLED" = "false" ]; then
          echo "skip_push=true" >> $GITHUB_OUTPUT
          echo "âš ï¸  Push disabled via workflow input"
        elif [ -z "$REGISTRY_PASSWORD" ]; then
          echo "skip_push=true" >> $GITHUB_OUTPUT
          echo "âš ï¸  Registry credentials not available - will build but skip push"
        else
          echo "skip_push=false" >> $GITHUB_OUTPUT
          echo "registry_username=$REGISTRY_USERNAME" >> $GITHUB_OUTPUT
          echo "âœ… Registry credentials available - will build and push"
        fi

    - name: Log in to Container Registry
      if: steps.check_creds.outputs.skip_push == 'false'
      env:
        REGISTRY_USERNAME: ${{ steps.check_creds.outputs.registry_username }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}
      run: |
        echo "ðŸ”‘ Logging in to registry: ${{ env.REGISTRY }} as $REGISTRY_USERNAME"
        echo "$REGISTRY_PASSWORD" | docker login "${{ env.REGISTRY }}" --username "$REGISTRY_USERNAME" --password-stdin
        echo "âœ… Registry login successful"

    - name: Build and push multi-arch image
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        BRANCH="${{ steps.version.outputs.branch }}"
        TARGET="${{ matrix.target.name }}"
        SUFFIX="${{ matrix.target.suffix }}"
        IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}"
        
        # Determine platform(s) to build
        if [ "${{ steps.check_creds.outputs.skip_push }}" = "false" ]; then
          PLATFORMS="linux/amd64,linux/arm64"
          echo "ðŸ—ï¸  Building multi-architecture image with Docker Buildx..."
        else
          # When building locally without push, only build for native platform
          # to avoid the "--load only supports single platform" error
          NATIVE_ARCH=$(uname -m)
          if [ "$NATIVE_ARCH" = "x86_64" ]; then
            PLATFORMS="linux/amd64"
          elif [ "$NATIVE_ARCH" = "aarch64" ] || [ "$NATIVE_ARCH" = "arm64" ]; then
            PLATFORMS="linux/arm64"
          else
            PLATFORMS="linux/amd64"  # fallback
          fi
          echo "ðŸ—ï¸  Building for native platform only (no registry push)..."
        fi
        
        echo "ðŸ“¦ Target: $TARGET (${{ matrix.target.description }})"
        echo "ðŸ“¦ Image: $IMAGE_NAME"
        echo "ðŸ·ï¸  Version: $VERSION$SUFFIX"
        echo "ðŸ—ï¸  Platforms: $PLATFORMS"
        echo "ðŸŽ¨ Hugo version: ${{ env.HUGO_VERSION }}"
        
        # Build tag list
        TAGS="-t ${IMAGE_NAME}:${VERSION}${SUFFIX}"
        
        # Add branch tag if not a release tag
        if [[ ! $GITHUB_REF == refs/tags/* ]]; then
          TAGS="$TAGS -t ${IMAGE_NAME}:${BRANCH}${SUFFIX}"
        fi
        
        # Add 'latest' tag for minimal target on version tags
        if [[ $GITHUB_REF == refs/tags/* ]] && [[ "$SUFFIX" == "" ]]; then
          TAGS="$TAGS -t ${IMAGE_NAME}:latest"
        fi
        
        echo "ðŸ·ï¸  Tags: $TAGS"
        
        # Build arguments
        BUILD_ARGS="--platform $PLATFORMS"
        BUILD_ARGS="$BUILD_ARGS --target $TARGET"
        BUILD_ARGS="$BUILD_ARGS --build-arg VERSION=$VERSION"
        BUILD_ARGS="$BUILD_ARGS --build-arg HUGO_VERSION=${{ env.HUGO_VERSION }}"
        BUILD_ARGS="$BUILD_ARGS --file Dockerfile"
        
        if [ "${{ steps.check_creds.outputs.skip_push }}" = "false" ]; then
          BUILD_ARGS="$BUILD_ARGS --push"
          echo "ðŸ“¤ Will push to registry"
        else
          BUILD_ARGS="$BUILD_ARGS --load"
          echo "ðŸ’¾ Will build and load locally for native platform"
        fi
        
        # Build image with Docker Buildx
        docker buildx build $BUILD_ARGS $TAGS .
        
        if [ "${{ steps.check_creds.outputs.skip_push }}" = "true" ]; then
          echo "â­ï¸  Skipping push (no registry credentials or push disabled)"
          echo "ðŸ“‹ Built image locally for $PLATFORMS"
          echo "ðŸ’¡ To build multi-arch, configure registry credentials and enable push"
        else
          echo "âœ… Multi-arch build and push completed successfully!"
          echo "ðŸ“‹ Available at: $IMAGE_NAME:$VERSION$SUFFIX"
        fi

    - name: Build summary
      if: always()
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        SUFFIX="${{ matrix.target.suffix }}"
        IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}"
        
        echo "## ðŸ—ï¸ Build Summary - ${{ matrix.target.name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Target**: \`${{ matrix.target.name }}\` (${{ matrix.target.description }})" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: \`$IMAGE_NAME:$VERSION$SUFFIX\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Platforms**: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
        echo "- **Hugo Version**: ${{ env.HUGO_VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Builder**: Docker Buildx (native multi-arch)" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.check_creds.outputs.skip_push }}" = "true" ]; then
          echo "- **Status**: âš ï¸ Built locally for native platform only" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ðŸ’¡ Multi-Architecture Builds" >> $GITHUB_STEP_SUMMARY
          echo "Local builds use \`--load\` which only supports single platform." >> $GITHUB_STEP_SUMMARY
          echo "To build for multiple architectures (amd64 + arm64), configure registry credentials:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- \`REGISTRY_USERNAME\`: Your registry username" >> $GITHUB_STEP_SUMMARY
          echo "- \`REGISTRY_PASSWORD\`: Your registry password/token" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Status**: âœ… Built and pushed successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Using the Image" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`yaml" >> $GITHUB_STEP_SUMMARY
          echo "# docker-compose.yml" >> $GITHUB_STEP_SUMMARY
          echo "services:" >> $GITHUB_STEP_SUMMARY
          echo "  docbuilder:" >> $GITHUB_STEP_SUMMARY
          echo "    image: $IMAGE_NAME:$VERSION$SUFFIX" >> $GITHUB_STEP_SUMMARY
          echo "    volumes:" >> $GITHUB_STEP_SUMMARY
          echo "      - ./config.yaml:/config/config.yaml" >> $GITHUB_STEP_SUMMARY
          echo "      - ./output:/data" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        fi

  build-complete:
    runs-on: dind
    needs: build-and-push
    if: always()
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Extract version info
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=$(git rev-parse --short=7 HEAD)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Final Summary
      run: |
        echo "## ðŸŽ‰ Multi-Arch Build Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Minimal runtime variant has been built:" >> $GITHUB_STEP_SUMMARY
        echo "- **Minimal**: Distroless base, smallest footprint, includes Go and Git from builder" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Available Image" >> $GITHUB_STEP_SUMMARY
        echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ steps.version.outputs.version }}\` (minimal)" >> $GITHUB_STEP_SUMMARY
