name: CI

on:
  push:
    branches: [ main ]
    paths-ignore: ['**.md']
  pull_request:
    branches: [ main ]
    paths-ignore: ['**.md']

env:
  REGISTRY: git.home.luguber.info
  IMAGE_NAME: docbuilder

jobs:
  test:
    name: Test & Lint (Quick Check)
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            git make ca-certificates curl && \
          update-ca-certificates

      - name: Checkout code (manual)
        run: |
          set -euo pipefail
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          if [ -n "${GITHUB_TOKEN:-}" ]; then
            HOST="${GITHUB_SERVER_URL#https://}"
            REPO_URL="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${HOST}/${GITHUB_REPOSITORY}.git"
          fi
          git init .
          git remote add origin "$REPO_URL"
          git fetch --depth=1 origin "${GITHUB_SHA}" || git fetch --depth=1 origin "${GITHUB_REF_NAME}"
          git checkout -qf FETCH_HEAD || git checkout -qf "${GITHUB_SHA}" || git checkout -qf "${GITHUB_REF_NAME}"

      - name: Download golangci-lint
        run: |
          GOLANGCI_VERSION="1.64.8"
          # Detect architecture
          case "$(uname -m)" in
            x86_64) GOLANGCI_ARCH="amd64" ;;
            aarch64|arm64) GOLANGCI_ARCH="arm64" ;;
            *) echo "Unsupported architecture: $(uname -m)"; exit 1 ;;
          esac
          echo "Installing golangci-lint ${GOLANGCI_VERSION} for linux-${GOLANGCI_ARCH}"
          curl -sSfL "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_VERSION}/golangci-lint-${GOLANGCI_VERSION}-linux-${GOLANGCI_ARCH}.tar.gz" | tar -xz -C /tmp
          cp /tmp/golangci-lint-${GOLANGCI_VERSION}-linux-${GOLANGCI_ARCH}/golangci-lint /usr/local/bin/
          
      - name: Quick format check
        run: |
          gofmt -l . | tee fmt-issues
          if [ -s fmt-issues ]; then
            echo "Code is not formatted. Please run 'make fmt'"
            cat fmt-issues
            exit 1
          fi

      - name: Quick lint check
        run: golangci-lint run --timeout=5m

      - name: Quick test (no race, no coverage)
        run: go test -short ./...

  build-and-test:
    name: Build & Full Test
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            git make ca-certificates curl && \
          sudo update-ca-certificates

      - name: Checkout code (manual)
        run: |
          set -euo pipefail
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          if [ -n "${GITHUB_TOKEN:-}" ]; then
            HOST="${GITHUB_SERVER_URL#https://}"
            REPO_URL="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${HOST}/${GITHUB_REPOSITORY}.git"
          fi
          git init .
          git remote add origin "$REPO_URL"
          git fetch --depth=1 origin "${GITHUB_SHA}" || git fetch --depth=1 origin "${GITHUB_REF_NAME}"
          git checkout -qf FETCH_HEAD || git checkout -qf "${GITHUB_SHA}" || git checkout -qf "${GITHUB_REF_NAME}"

      - name: Download Docker Buildx
        run: |
          BUILDX_VERSION="0.19.0"
          # Detect architecture for runner
          case "$(uname -m)" in
            x86_64) BUILDX_ARCH="amd64" ;;
            aarch64|arm64) BUILDX_ARCH="arm64" ;;
            *) echo "Unsupported architecture: $(uname -m)"; exit 1 ;;
          esac
          echo "Installing docker buildx ${BUILDX_VERSION} for linux-${BUILDX_ARCH}"
          
          # Download and install buildx
          mkdir -p ~/.docker/cli-plugins
          curl -sSfL "https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-${BUILDX_ARCH}" \
            -o ~/.docker/cli-plugins/docker-buildx
          chmod +x ~/.docker/cli-plugins/docker-buildx
          
          # Set up buildx
          docker buildx create --name multiarch --driver docker-container --use || true
          docker buildx inspect --bootstrap

      - name: Compute image tags
        id: tags
        run: |
          set -euo pipefail
          IMAGE_BASE="${REGISTRY}/${GITHUB_REPOSITORY_OWNER}/${IMAGE_NAME}"
          SHA_TAG="${GITHUB_SHA}"
          BRANCH_TAG="${GITHUB_REF_NAME//\//-}"
          echo "image_base=${IMAGE_BASE}" >> $GITHUB_OUTPUT
          echo "sha_tag=${SHA_TAG}" >> $GITHUB_OUTPUT
          echo "branch_tag=${BRANCH_TAG}" >> $GITHUB_OUTPUT

      - name: Build and test with Docker Buildx
        run: |
          # Build the image (includes all tests, format checks, linting, and binary build)
          if [ "${GITHUB_EVENT_NAME}" != "pull_request" ] && [ -n "${{ secrets.REGISTRY_TOKEN }}" ]; then
            # Login to registry
            echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            
            # Build and push
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag ${{ steps.tags.outputs.image_base }}:${{ steps.tags.outputs.sha_tag }} \
              --tag ${{ steps.tags.outputs.image_base }}:${{ steps.tags.outputs.branch_tag }} \
              --push \
              .
            
            echo "✅ Multi-arch image built and pushed to registry"
          else
            # Build only (no push for PRs or without registry token)
            docker buildx build \
              --platform linux/amd64 \
              --tag ${{ steps.tags.outputs.image_base }}:${{ steps.tags.outputs.sha_tag }} \
              --tag ${{ steps.tags.outputs.image_base }}:${{ steps.tags.outputs.branch_tag }} \
              --load \
              .
            
            echo "✅ Image built successfully (no push for PR)"
          fi

      - name: Log build results
        run: |
          echo "=== Build Summary ==="
          echo "Image: ${{ steps.tags.outputs.image_base }}:${{ steps.tags.outputs.sha_tag }}"
          echo "All tests, linting, format checks, and build completed successfully in Dockerfile"
          if [ "${GITHUB_EVENT_NAME}" != "pull_request" ] && [ -n "${{ secrets.REGISTRY_TOKEN }}" ]; then
            echo "Multi-arch images pushed to registry: ${{ env.REGISTRY }}"
            echo "Platforms: linux/amd64, linux/arm64"
          fi