name: CI

on:
  push:
    branches: [ main ]
    paths-ignore: ['**.md']
  pull_request:
    branches: [ main ]
    paths-ignore: ['**.md']

env:
  REGISTRY: git.home.luguber.info
  IMAGE_NAME: docbuilder

jobs:
  test:
    name: Test & Lint (Quick Check)
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            git make ca-certificates curl && \
          update-ca-certificates

      - name: Checkout code (manual)
        run: |
          set -euo pipefail
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          if [ -n "${GITHUB_TOKEN:-}" ]; then
            HOST="${GITHUB_SERVER_URL#https://}"
            REPO_URL="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${HOST}/${GITHUB_REPOSITORY}.git"
          fi
          git init .
          git remote add origin "$REPO_URL"
          git fetch --depth=1 origin "${GITHUB_SHA}" || git fetch --depth=1 origin "${GITHUB_REF_NAME}"
          git checkout -qf FETCH_HEAD || git checkout -qf "${GITHUB_SHA}" || git checkout -qf "${GITHUB_REF_NAME}"

      - name: Download golangci-lint
        run: |
          GOLANGCI_VERSION="1.64.8"
          # Detect architecture
          case "$(uname -m)" in
            x86_64) GOLANGCI_ARCH="amd64" ;;
            aarch64|arm64) GOLANGCI_ARCH="arm64" ;;
            *) echo "Unsupported architecture: $(uname -m)"; exit 1 ;;
          esac
          echo "Installing golangci-lint ${GOLANGCI_VERSION} for linux-${GOLANGCI_ARCH}"
          curl -sSfL "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_VERSION}/golangci-lint-${GOLANGCI_VERSION}-linux-${GOLANGCI_ARCH}.tar.gz" | tar -xz -C /tmp
          cp /tmp/golangci-lint-${GOLANGCI_VERSION}-linux-${GOLANGCI_ARCH}/golangci-lint /usr/local/bin/
          
      - name: Quick format check
        run: |
          gofmt -l . | tee fmt-issues
          if [ -s fmt-issues ]; then
            echo "Code is not formatted. Please run 'make fmt'"
            cat fmt-issues
            exit 1
          fi

      - name: Quick lint check
        run: golangci-lint run --timeout=5m

      - name: Quick test (no race, no coverage)
        run: go test -short ./...

  build-and-test:
    name: Build & Full Test
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            git make ca-certificates curl && \
          update-ca-certificates

      - name: Checkout code (manual)
        run: |
          set -euo pipefail
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          if [ -n "${GITHUB_TOKEN:-}" ]; then
            HOST="${GITHUB_SERVER_URL#https://}"
            REPO_URL="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${HOST}/${GITHUB_REPOSITORY}.git"
          fi
          git init .
          git remote add origin "$REPO_URL"
          git fetch --depth=1 origin "${GITHUB_SHA}" || git fetch --depth=1 origin "${GITHUB_REF_NAME}"
          git checkout -qf FETCH_HEAD || git checkout -qf "${GITHUB_SHA}" || git checkout -qf "${GITHUB_REF_NAME}"

      - name: Download tools with architecture detection
        run: |
          HUGO_VERSION="0.151.0"
          GOLANGCI_VERSION="1.64.8"
          # Detect architecture
          case "$(uname -m)" in
            x86_64) ARCH="amd64" ;;
            aarch64|arm64) ARCH="arm64" ;;
            *) echo "Unsupported architecture: $(uname -m)"; exit 1 ;;
          esac
          
          echo "Installing Hugo ${HUGO_VERSION} for linux-${ARCH}"
          curl -sSfL "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-${ARCH}.tar.gz" | tar -xz -C /tmp
          cp /tmp/hugo /usr/local/bin/
          hugo version
          
          echo "Installing golangci-lint ${GOLANGCI_VERSION} for linux-${ARCH}"
          curl -sSfL "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_VERSION}/golangci-lint-${GOLANGCI_VERSION}-linux-${ARCH}.tar.gz" | tar -xz -C /tmp
          cp /tmp/golangci-lint-${GOLANGCI_VERSION}-linux-${ARCH}/golangci-lint /usr/local/bin/

      - name: Download dependencies
        run: make deps

      - name: Format check
        run: |
          make fmt
          if [ -n "$(git diff --name-only)" ]; then
            echo "Code is not formatted. Please run 'make fmt'"
            git diff
            exit 1
          fi

      - name: Lint
        run: make lint

      - name: Run tests with coverage
        run: make test-coverage

      - name: Show coverage summary
        run: |
          if [ -f coverage.out ]; then
            go tool cover -func=coverage.out | tail -n 1 || true
          fi

      - name: Build binary
        run: make build

      - name: Test binary execution
        run: |
          ./bin/docbuilder --version
          ./bin/docbuilder --help

      - name: Show build results
        run: |
          echo "=== Build Summary ==="
          echo "✅ Format check passed"
          echo "✅ Lint check passed" 
          echo "✅ Tests passed with coverage"
          echo "✅ Binary built successfully"
          ls -lh bin/docbuilder || true
          echo ""
          echo "Note: Container image build skipped in favor of direct binary build"
          echo "This approach avoids Docker daemon complexity while maintaining full testing"